using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MongoDBModel.Enum
{
    public enum ReasonActionGold
    {
        None = 0,
        // get
        RewardAttackStage = 1,
        RewardCreateAccount = 2,
        RewardCauCa = 3,
        RewardCuopTieu = 4,
        RewardInvitedFriend = 5,
        RewardSk7NgayNhanThuong = 6,
        RewardTutorial = 7,
        RewardDiemDanh = 8,
        RewardLevel = 9,
        RewardLuanKiemRank = 10,
        RewardMail = 11,
        RewardNhiemVuChinhTuyen = 12,
        RewardPointSkDoiDo = 13,
        RewardPhucLoiTruongThanh = 14,
        RewardPointSkVongQuayMayMan = 15,
        RewardSkRotDo = 16,
        RewardChucPhuc = 17,
        RewardAttackGlobalBoss = 18,
        RewardExchangeItem = 19,
        RewardCuuCuuTriTon = 20,
        RewardNhiemVuHangNgay = 21,
        RewardRuongBau = 22,
        RewardStarMap = 23,
        RewardSkTichLuyNap = 24,
        RewardSkTichLuyTieu = 25,
        RewardSkVongQuayMayMan = 26,
        RewardSharedFacebook = 27,
        RewardVanTieu = 28,
        RewardVip = 29,
        RewardLuaTrai = 30,
        RewardMoRuong = 31,
        RewardGiftCode = 32,
        ExchangeRubyToGold = 33,
        ThangDoPhuong = 34,
        RewardThanTai = 35,
        // spent
        BuyLeBao,
        BuyShopItem,
        QuayTuongx10,
        QuayTuongx1,
        PlushAttributeGlobalBoss,
        ResetUpPointChar,
        UpPointChar,
        BuyThuongNhanKyBi,
        GetVehicleVanTieu,
        QuickEndVanTieu,
        ResetThanThap,
        BaoThuCuopBiKip,
        BuyMissingRewardDiemDanh,
        ResetPhuBan,
        ResetStage,
        GetRewardPhuBan,
        QuayVatPhamx10,
        ResetLuanKiem,
        ThuaDoPhuong,
        StartCauCa,
        QuickFinishMissionGuild,
        CreateGuild,
        UpContributeGuild,
        GetRewardSkVongQuayMayMan,
        QuayVatPhamx1,
        QuickFinishNhiemVuHangNgay,
        SkDoiDo,
        BuyItemTranhMuaServer,
        RefeshDoiDo,
        SellItemOnMarket,
        BuyItemOnMarket,
        QuickEndCauCa,
        ExchangeGoldToSilver,
        RewardAttackLuanKiem,
        BuyPointSkill,
        ExchangeGoldInSkRotDo,
        ExchangeSilverInSkRotDo
    }
}
