
namespace MongoDBModel.Enum
{
    public enum TypeUseGold
    {
        None,
        BuyLeBao,
        BuyShopItem,
        QuayTuongx10,
        QuayTuongx1,
        PlushAttributeGlobalBoss,
        ResetUpPointChar,
        UpPointChar,
        BuyThuongNhanKyBi,
        GetVehicleVanTieu,
        QuickEndVanTieu,
        ResetThanThap,
        BaoThuCuopBiKip,
        BuyMissingRewardDiemDanh,
        ResetPhuBan,
        ResetStage,
        GetRewardPhuBan,
        QuayVatPhamx10,
        ResetLuanKiem,
        ThuaDoXucXac,
        StartCauCa,
        QuickFinishMissionGuild,
        CreateGuild,
        UpContributeGuild,
        GetRewardSkVongQuayMayMan,
        QuayVatPhamx1,
        QuickFinishNhiemVuHangNgay,
        SkDoiDo,
        BuyItemTranhMuaServer,
        RefeshDoiDo,
        SellItemOnMarket,
        BuyItemOnMarket,
        QuickEndCauCa,
        ExchangeGoldToSilver
    }
}
