//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbBattleConfig
    {
        public int id { get; set; }
        public Nullable<int> maxTurn { get; set; }
        public Nullable<double> centerBattleX { get; set; }
        public Nullable<double> centerBattleY { get; set; }
        public Nullable<double> distanceFrontTarget { get; set; }
        public Nullable<int> manaPool { get; set; }
        public Nullable<int> manaRegen { get; set; }
        public Nullable<int> manaRegenUltimate { get; set; }
        public Nullable<int> idBachgroundThachDau { get; set; }
        public Nullable<int> idBossWorld { get; set; }
        public Nullable<int> idBachgroundThanThap { get; set; }
        public Nullable<int> idBachgroundBoss { get; set; }
        public Nullable<int> idBackgroundCuopTieu { get; set; }
        public Nullable<int> idBackgroundLuanKiem { get; set; }
        public Nullable<int> idBackgroundBangChien { get; set; }
        public Nullable<int> manaRegenAttacked { get; set; }
        public Nullable<int> levelSpeed { get; set; }
        public Nullable<int> vipAuto { get; set; }
        public Nullable<int> vipSpeed { get; set; }
        public Nullable<int> rangeRandomDamage { get; set; }
    }
}
