//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCTDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbCharacter
    {
        public int id { get; set; }
        public Nullable<int> idCharacter { get; set; }
        public string name { get; set; }
        public string descriptions { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> classCharacter { get; set; }
        public Nullable<int> isCreep { get; set; }
        public Nullable<int> idCharHuaNguyen { get; set; }
        public Nullable<int> isMale { get; set; }
        public Nullable<int> element { get; set; }
        public Nullable<int> idGroup { get; set; }
        public string quote { get; set; }
        public Nullable<int> typeCharacter { get; set; }
        public Nullable<int> lowestStarLevel { get; set; }
        public Nullable<int> highestStarLevel { get; set; }
        public Nullable<int> orders { get; set; }
        public Nullable<int> status { get; set; }
    }
}
