//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCTDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbCharSkillStarLevel
    {
        public int id { get; set; }
        public Nullable<int> star { get; set; }
        public Nullable<int> numberItemRequire { get; set; }
        public Nullable<int> silverRequire { get; set; }
        public Nullable<int> maxLevel { get; set; }
        public Nullable<int> status { get; set; }
    }
}
