//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCTDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbCharacterConfig
    {
        public int id { get; set; }
        public Nullable<int> maxStarCanUp { get; set; }
        public Nullable<int> amountCharToSoul { get; set; }
        public Nullable<int> powerUpLevelUnlockPassiveSkill { get; set; }
        public Nullable<int> levelUnlockPassiveSkill2 { get; set; }
        public Nullable<int> prefixSilverUpSkill { get; set; }
        public Nullable<double> modStar { get; set; }
        public Nullable<double> procReceivedUpStar { get; set; }
        public Nullable<double> procAmountCharToSoul { get; set; }
    }
}
