//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbCharDefaultConfig
    {
        public int id { get; set; }
        public Nullable<int> idChrConfig { get; set; }
        public Nullable<int> levelSkill { get; set; }
        public Nullable<int> levelChar { get; set; }
        public Nullable<int> promotionLevelChar { get; set; }
        public Nullable<int> powerupLevelChar { get; set; }
        public Nullable<int> starLevelChar { get; set; }
    }
}
