//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCTDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbCuuCuuTriTonConfig
    {
        public dbCuuCuuTriTonConfig()
        {
            this.dbCuuCuuTriTonConfigRewards = new HashSet<dbCuuCuuTriTonConfigReward>();
        }
    
        public int id { get; set; }
        public Nullable<int> ruby_require { get; set; }
        public Nullable<int> duration { get; set; }
    
        public virtual ICollection<dbCuuCuuTriTonConfigReward> dbCuuCuuTriTonConfigRewards { get; set; }
    }
}
