//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbDoiHinhDuBiRequire
    {
        public int id { get; set; }
        public Nullable<int> numberItem { get; set; }
        public Nullable<int> levels { get; set; }
        public Nullable<int> status { get; set; }
    }
}
