//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCTDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbEquipment
    {
        public dbEquipment()
        {
            this.dbEquipmentAttributes = new HashSet<dbEquipmentAttribute>();
            this.dbEquipmentStarUps = new HashSet<dbEquipmentStarUp>();
        }
    
        public int id { get; set; }
        public Nullable<int> idEquipment { get; set; }
        public string name { get; set; }
        public string descriptions { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> promotion { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> baseMarketPrice { get; set; }
        public Nullable<int> canSellMarket { get; set; }
        public Nullable<int> icon { get; set; }
    
        public virtual ICollection<dbEquipmentAttribute> dbEquipmentAttributes { get; set; }
        public virtual ICollection<dbEquipmentStarUp> dbEquipmentStarUps { get; set; }
    }
}
