//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCTDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbEquipmentElementAttribute
    {
        public int id { get; set; }
        public Nullable<int> idEquipment { get; set; }
        public Nullable<int> element { get; set; }
        public Nullable<int> status { get; set; }
    }
}
