//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCTDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbEquipment
    {
        public int id { get; set; }
        public Nullable<int> idEquipment { get; set; }
        public Nullable<int> icon { get; set; }
        public string name { get; set; }
        public string descriptions { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> baseMarketPrice { get; set; }
        public Nullable<int> canSellMarket { get; set; }
        public Nullable<int> lowestStarLevel { get; set; }
        public Nullable<int> highestStarLevel { get; set; }
        public Nullable<int> attAttribute { get; set; }
        public Nullable<double> attMods { get; set; }
        public Nullable<int> attGrowthMod { get; set; }
        public Nullable<int> status { get; set; }
    }
}
