//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCTDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbEquipmentBonusAttribute
    {
        public int id { get; set; }
        public Nullable<int> idElement { get; set; }
        public Nullable<int> attribute { get; set; }
        public Nullable<double> minMod { get; set; }
        public Nullable<double> maxMod { get; set; }
        public Nullable<double> minGrowMod { get; set; }
        public Nullable<double> maxGrowMod { get; set; }
        public Nullable<double> procs { get; set; }
        public Nullable<int> status { get; set; }
    }
}
