//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbExchangeGoldToSilverConfig
    {
        public int id { get; set; }
        public Nullable<int> levelRequire { get; set; }
        public Nullable<int> freeTimes { get; set; }
        public Nullable<double> procBonusSilver { get; set; }
        public Nullable<double> bonusSilver { get; set; }
        public Nullable<double> stepUpGold { get; set; }
        public Nullable<int> baseGold { get; set; }
        public Nullable<int> baseSilver { get; set; }
    }
}
