//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCTDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbFreeStaminaConfig
    {
        public int id { get; set; }
        public Nullable<int> froms { get; set; }
        public Nullable<int> tos { get; set; }
        public Nullable<int> stamina { get; set; }
        public Nullable<int> status { get; set; }
    }
}
