//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbGlobalBossConfig
    {
        public dbGlobalBossConfig()
        {
            this.dbGlobalAttackConfigs = new HashSet<dbGlobalAttackConfig>();
            this.dbGlobalBonusRewardConfigs = new HashSet<dbGlobalBonusRewardConfig>();
        }
    
        public int id { get; set; }
        public Nullable<int> idConfig { get; set; }
        public Nullable<int> hourStart { get; set; }
        public Nullable<int> minuteStart { get; set; }
        public Nullable<int> hourEnd { get; set; }
        public Nullable<int> minuteEnd { get; set; }
        public Nullable<int> levelRequire { get; set; }
        public Nullable<int> hpBossAtLevel { get; set; }
        public Nullable<int> growthHp { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual dbConfig dbConfig { get; set; }
        public virtual ICollection<dbGlobalAttackConfig> dbGlobalAttackConfigs { get; set; }
        public virtual ICollection<dbGlobalBonusRewardConfig> dbGlobalBonusRewardConfigs { get; set; }
    }
}
