//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCTDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbGuildMission
    {
        public int id { get; set; }
        public Nullable<int> idGuild { get; set; }
        public string name { get; set; }
        public Nullable<int> durationMinutes { get; set; }
        public Nullable<int> contribute { get; set; }
        public Nullable<int> contributeMember { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual dbGuildConfig dbGuildConfig { get; set; }
    }
}
