//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbHoatDongDiemDanhConfig
    {
        public dbHoatDongDiemDanhConfig()
        {
            this.dbHoatDongDiemDanhMonths = new HashSet<dbHoatDongDiemDanhMonth>();
        }
    
        public int id { get; set; }
        public Nullable<int> idConfig { get; set; }
        public Nullable<int> goldRequireBuyMissingReward { get; set; }
    
        public virtual dbConfig dbConfig { get; set; }
        public virtual ICollection<dbHoatDongDiemDanhMonth> dbHoatDongDiemDanhMonths { get; set; }
    }
}
