//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCTDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbInviteFriendConfig
    {
        public dbInviteFriendConfig()
        {
            this.dbInviteFriendRewards = new HashSet<dbInviteFriendReward>();
        }
    
        public int id { get; set; }
        public Nullable<int> require { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual ICollection<dbInviteFriendReward> dbInviteFriendRewards { get; set; }
    }
}
