//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbItem
    {
        public dbItem()
        {
            this.dbItemAttributes = new HashSet<dbItemAttribute>();
        }
    
        public int id { get; set; }
        public Nullable<int> idItem { get; set; }
        public string name { get; set; }
        public string descriptions { get; set; }
        public Nullable<double> sellPrice { get; set; }
        public Nullable<int> types { get; set; }
        public Nullable<int> border { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual ICollection<dbItemAttribute> dbItemAttributes { get; set; }
    }
}
