//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbLuanKiemConfig
    {
        public dbLuanKiemConfig()
        {
            this.dbLuanKiemPoints = new HashSet<dbLuanKiemPoint>();
            this.dbLuanKiemRanges = new HashSet<dbLuanKiemRange>();
            this.dbLuanKiemRanks = new HashSet<dbLuanKiemRank>();
        }
    
        public int id { get; set; }
        public Nullable<int> idConfig { get; set; }
        public Nullable<int> levelRequire { get; set; }
        public Nullable<int> freeTimesAttack { get; set; }
        public Nullable<int> timeMinutesCoolDownPlusLuanKiemPoint { get; set; }
        public Nullable<int> hourSendGift { get; set; }
        public Nullable<int> minuteSendGift { get; set; }
        public Nullable<int> timeMinutesCoolDownAttackLuanKiem { get; set; }
        public Nullable<int> timeMinutesCoolDownAttack { get; set; }
        public Nullable<int> goldRequireQuickAttack { get; set; }
    
        public virtual dbConfig dbConfig { get; set; }
        public virtual ICollection<dbLuanKiemPoint> dbLuanKiemPoints { get; set; }
        public virtual ICollection<dbLuanKiemRange> dbLuanKiemRanges { get; set; }
        public virtual ICollection<dbLuanKiemRank> dbLuanKiemRanks { get; set; }
    }
}
