//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCTDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbLuanKiemRangeOpponent
    {
        public int id { get; set; }
        public Nullable<int> idRange { get; set; }
        public Nullable<int> rangeStart { get; set; }
        public Nullable<int> rangeEnd { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual dbLuanKiemRange dbLuanKiemRange { get; set; }
    }
}
