//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBCTDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbMapStage
    {
        public dbMapStage()
        {
            this.dbMapStageMonters = new HashSet<dbMapStageMonter>();
            this.dbMapStageMonterSuppers = new HashSet<dbMapStageMonterSupper>();
            this.dbMapStagePaths = new HashSet<dbMapStagePath>();
            this.dbMapStageRewards = new HashSet<dbMapStageReward>();
            this.dbMapStageSuppers = new HashSet<dbMapStageSupper>();
        }
    
        public int id { get; set; }
        public Nullable<int> idMap { get; set; }
        public string name { get; set; }
        public string descriptions { get; set; }
        public Nullable<int> typeStage { get; set; }
        public Nullable<int> maxAttack { get; set; }
        public Nullable<int> silverRewardMin { get; set; }
        public Nullable<int> silverRewardMax { get; set; }
        public Nullable<int> expRewardMin { get; set; }
        public Nullable<int> expRewardMax { get; set; }
        public Nullable<int> stamina { get; set; }
        public Nullable<int> expPlayer { get; set; }
        public Nullable<double> totalPower { get; set; }
        public Nullable<double> positionX { get; set; }
        public Nullable<double> positionY { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> background { get; set; }
    
        public virtual dbMap dbMap { get; set; }
        public virtual ICollection<dbMapStageMonter> dbMapStageMonters { get; set; }
        public virtual ICollection<dbMapStageMonterSupper> dbMapStageMonterSuppers { get; set; }
        public virtual ICollection<dbMapStagePath> dbMapStagePaths { get; set; }
        public virtual ICollection<dbMapStageReward> dbMapStageRewards { get; set; }
        public virtual ICollection<dbMapStageSupper> dbMapStageSuppers { get; set; }
    }
}
