//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbNhiemVuChinhTuyen
    {
        public dbNhiemVuChinhTuyen()
        {
            this.dbNhiemVuChinhTuyenRewards = new HashSet<dbNhiemVuChinhTuyenReward>();
        }
    
        public int id { get; set; }
        public Nullable<int> idChinhTuyen { get; set; }
        public Nullable<int> idNhiemVu { get; set; }
        public Nullable<int> types { get; set; }
        public string name { get; set; }
        public string des { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> stepUpNumber { get; set; }
        public Nullable<int> numberRequire { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual dbNhiemVuChinhTuyenConfig dbNhiemVuChinhTuyenConfig { get; set; }
        public virtual ICollection<dbNhiemVuChinhTuyenReward> dbNhiemVuChinhTuyenRewards { get; set; }
    }
}
