//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbNhiemVuChinhTuyenConfig
    {
        public dbNhiemVuChinhTuyenConfig()
        {
            this.dbNhiemVuChinhTuyens = new HashSet<dbNhiemVuChinhTuyen>();
        }
    
        public int id { get; set; }
        public Nullable<int> idConfig { get; set; }
    
        public virtual dbConfig dbConfig { get; set; }
        public virtual ICollection<dbNhiemVuChinhTuyen> dbNhiemVuChinhTuyens { get; set; }
    }
}
