//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHDesignerTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbVipConfig
    {
        public int id { get; set; }
        public Nullable<int> goldRequire { get; set; }
        public Nullable<int> arenaTimes { get; set; }
        public Nullable<int> challengeTimes { get; set; }
        public Nullable<int> resetStageTimes { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> vip { get; set; }
        public Nullable<int> moiRuouTimes { get; set; }
        public Nullable<int> vanTieuTimes { get; set; }
        public Nullable<int> cauCaTimes { get; set; }
        public Nullable<int> doPhuongTimes { get; set; }
        public Nullable<int> cuopTieuTimes { get; set; }
        public Nullable<int> maxSellMarket { get; set; }
        public Nullable<int> exchangeGoldToSilverTimes { get; set; }
        public Nullable<int> huaNguyenTimes { get; set; }
        public Nullable<int> buyPointSkillTimes { get; set; }
    }
}
