//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHNPHTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbCauCaConfig
    {
        public dbCauCaConfig()
        {
            this.dbCauCaRewards = new HashSet<dbCauCaReward>();
        }
    
        public int id { get; set; }
        public Nullable<int> idConfig { get; set; }
        public string name { get; set; }
        public Nullable<int> gold { get; set; }
        public Nullable<int> silver { get; set; }
        public Nullable<int> vipRequire { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual dbConfig dbConfig { get; set; }
        public virtual ICollection<dbCauCaReward> dbCauCaRewards { get; set; }
    }
}
