//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHNPHTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbCharDuyenPhan
    {
        public dbCharDuyenPhan()
        {
            this.dbCharDuyenPhanAttributes = new HashSet<dbCharDuyenPhanAttribute>();
            this.dbCharDuyenPhanIDS = new HashSet<dbCharDuyenPhanID>();
        }
    
        public int id { get; set; }
        public Nullable<int> idCharacter { get; set; }
        public Nullable<int> category { get; set; }
        public string name { get; set; }
        public Nullable<int> isOne { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual dbCharacter dbCharacter { get; set; }
        public virtual ICollection<dbCharDuyenPhanAttribute> dbCharDuyenPhanAttributes { get; set; }
        public virtual ICollection<dbCharDuyenPhanID> dbCharDuyenPhanIDS { get; set; }
    }
}
