//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHNPHTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbHoatDongDiemDanhMonth
    {
        public dbHoatDongDiemDanhMonth()
        {
            this.dbHoatDongDiemDanhMonthRewards = new HashSet<dbHoatDongDiemDanhMonthReward>();
        }
    
        public int id { get; set; }
        public Nullable<int> idDiemDanh { get; set; }
        public Nullable<int> months { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual dbHoatDongDiemDanhConfig dbHoatDongDiemDanhConfig { get; set; }
        public virtual ICollection<dbHoatDongDiemDanhMonthReward> dbHoatDongDiemDanhMonthRewards { get; set; }
    }
}
