//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHNPHTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbLogKNBTool
    {
        public int id { get; set; }
        public string nickTool { get; set; }
        public Nullable<int> hanhDong { get; set; }
        public string userName { get; set; }
        public string para { get; set; }
        public string paraLast { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
        public Nullable<int> status { get; set; }
        public string serverID { get; set; }
    }
}
