//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDQHNPHTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbStarReward
    {
        public dbStarReward()
        {
            this.dbStarRewardRewards = new HashSet<dbStarRewardReward>();
        }
    
        public int id { get; set; }
        public Nullable<int> starRequire { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual ICollection<dbStarRewardReward> dbStarRewardRewards { get; set; }
    }
}
